<div class="block block-news">
    <?php /* @var My\News\Block\News $block */ ?>
    <?php $news = $block->getNews(); ?>
    <div class="block-content">
        <h2><?php echo $block->escapeHtml($news->getTitle()) ?></h2>
        <span><?php echo $block->escapeHtml($block->getDate($news)) ?></span>
        <div class="news-content">
            <?php /* @noEscape */echo $news->getContent() ?>
        </div>
    </div>
</div>
