<div class="block block-news">
    <?php /* @var My\News\Block\News $block */ ?>
    <?php $news = $block->getCollection(); ?>
    <div class="block-content">
        <?php if (count($news) > 0): ?>
            <div class="table-wrapper news">
                <table class="data table table-news-items recent" id="news-table">
                    <caption class="table-caption"><?php /* @escapeNotVerified */ echo __('News') ?></caption>
                    <thead>
                    <tr>
                        <th scope="col" class="col title"><?php /* @escapeNotVerified */ echo __('Title') ?></th>
                        <th scope="col" class="col date"><?php /* @escapeNotVerified */ echo __('Date') ?></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($news as $_news): ?>
                        <tr>
                            <td data-th="<?php echo $block->escapeHtml(__('Title')) ?>" class="col title">
                                <a href="<?php echo $block->getUrl('mynews/index/detail', ['id' => $_news->getId()]);?>">
                                    <?php echo $block->escapeHtml($_news->getTitle()) ?>
                                </a>
                            </td>
                            <td data-th="<?php echo $block->escapeHtml(__('Date')) ?>" class="col date">
                                <?php echo $block->escapeHtml($block->getDate($_news)) ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
        <?php else: ?>
            <div class="message info empty"><span><?php /* @escapeNotVerified */ echo __('No news now.'); ?></span></div>
        <?php endif; ?>
    </div>
</div>
